- name: Install the required packages
  ansible.builtin.dnf:
    name: "{{ lvm_packages }}"
    state: latest

- name: Create the mount points
  file:
    path: "{{ lv_list[item.key].path }}"
    state: directory
  with_dict: "{{ lv_list }}"

- name: Create the volume group using the physical volumes
  lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ dev_path_by_id }}{{ pg_data_hdd }}"

- name: Create the logical volumes
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_list[item.key].lv_name }}"
    size: "{{ lv_list[item.key].size }}"
    resizefs: yes
  with_dict: "{{ lv_list }}"

- name: Create the filesystems on the logical volumes
  filesystem:
    fstype: "{{ lv_list[item.key].fs_type }}"
    dev: "/dev/{{ vg_name }}/{{ lv_list[item.key].lv_name }}"
    opts: "{{ lv_list[item.key].mkfs_opts|default('') }}"
  with_dict: "{{ lv_list }}"

- name: Set the mount status for the logical volumes
  mount:
    path: "{{ lv_list[item.key].path }}"
    src: "/dev/{{ vg_name }}/{{ lv_list[item.key].lv_name }}"
    fstype: "{{ lv_list[item.key].fs_type }}"
    opts: "{{ lv_list[item.key].fs_opt }}"
    state: mounted
  with_dict: "{{ lv_list }}"

- name: Create a new ext4 primary partition
  community.general.parted:
    device: "{{ dev_path_by_id }}{{ pg_ext4_hdd }}"
    number: 1
    state: present
    fs_type: "{{ tbs_ext4.fs_type }}"


- name: Create the filesystems on the ext4 partition
  filesystem:
    fstype: "{{ tbs_ext4.fs_type }}"
    dev: "{{ dev_path_by_id }}{{ pg_ext4_hdd }}-part1"

- name: Set the mount status for the logical volumes
  mount:
    path: "{{tbs_ext4.path}}"
    src: "{{ dev_path_by_id }}{{ pg_ext4_hdd }}-part1"
    fstype: "{{ tbs_ext4.fs_type }}"
    opts: "{{ tbs_ext4.fs_opt }}"
    state: mounted


