---
prom_packages:
  - golang-github-prometheus
  - grafana

prom_exporters:
  - golang-github-prometheus-node-exporter
  - golang-github-prometheus-procfs-devel


zip_binaries:
  - "bzip2"
  - "zstd"
postgresql_exporter_version: "0.15.0"
postgresql_exporter_file: "postgres_exporter-{{postgresql_exporter_version}}.linux-amd64.tar.gz"


postgresql_exporter_url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{postgresql_exporter_version}}/{{postgresql_exporter_file}}"

postgresql_exporter_link: "/opt/postgres_exporter"
postgresql_exporter_dir: "postgres_exporter-{{postgresql_exporter_version}}.linux-amd64"


zfs_exporter_version: "2.3.2"
zfs_exporter_file: "zfs_exporter-{{zfs_exporter_version}}.linux-amd64.tar.gz"

zfs_exporter_url: "https://github.com/pdf/zfs_exporter/releases/download/v{{zfs_exporter_version}}/{{zfs_exporter_file}}"

zfs_exporter_link: "/opt/zfs_exporter"
zfs_exporter_dir: "zfs_exporter-{{zfs_exporter_version}}.linux-amd64"



