---

- name: install the required packages 
  dnf:
    name: "{{ zfs_required_pkg }}"
    state: present

- name: add the gpg key to the rpm repository
  rpm_key:
    state: present
    key: "{{zfs_dnf_gpg_key}}"


- name: install the zfs repository
  dnf:
    name: "{{ zfs_repo_url }}"
    state: present


- name: Ensure zfs respository is disabled
  community.general.dnf_config_manager:
    name:
      - zfs
    state: disabled

- name: Ensure zfs-kmod respository is enabled
  community.general.dnf_config_manager:
    name:
      - zfs-kmod
    state: enabled

- name: install zfs
  dnf:
    name: "zfs"
    state: present

- name: Add the zfs module
  community.general.modprobe:
    name: zfs
    state: present

- name: Gather facts about ZFS pool rpool
  community.general.zpool_facts: 


- name: Print gathered information
  ansible.builtin.debug:
    msg: 'ZFS pool {{ item.name }} '
  with_items: '{{ ansible_zfs_pools }}'