- name: install the epel-release
  dnf:
    name: "epel-release"
    state: present

- name: install the built in exporters
  dnf:
    name: "{{prom_exporters}}"
    state: present

  
- name: install and configure the postgres exporter
  include_tasks: "postgres_exporter.yml"
  when: ansible_hostname in groups['postgresql']

